version: '3.8'

services:
  app:
    build: .
    container_name: springapp
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rpgnexus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rpgnexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network


  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: always
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger.yaml
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
